#include <GL/glew.h>
#include <GLFW/glfw3.h>
#include <glm/glm.hpp>
#include <iostream>
#include "../../objLoader/tiny_obj_loader.h"
#include <glm/gtc/matrix_transform.hpp>
#include "../../common/controls.h"
#include "../../common/shader.h"
#include <assert.h>
#include "../../common/texture.h"
#include <vector>
#include <string>
